$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
experiment_name: mlops-diabetes-training
display_name: test_data_and_train_model

inputs:
  test_data_folder:
    type: uri_folder
    path: azureml://datastores/workspaceblobstore/paths/
jobs:
  test_data:
    code: test-data
    command: python test_data.py --test_data ${{inputs.training_data}}
    environment: azureml:train-env@latest
    compute: azureml:aks-cluster
    inputs:
      training_data: ${{parent.inputs.test_data_folder}}
    description: Test the train data whether the columns are as expected.
    display_name: test_data
    outputs:
        test_data_output: ${{parent.inputs.test_data_folder}}
  train_model:
    code: model
    command: python train.py --training_data ${{inputs.training_data}} --reg_rate ${{inputs.reg_rate}}
    inputs:
      training_data: ${{parent.jobs.test_data.outputs.test_data_output}}
      reg_rate: 0.01
    environment: azureml:train-env@latest
    compute: azureml:aks-cluster
    description: Train a LR model with YML
    display_name: train_model