$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: test_data_and_train_model

inputs:
  test_data_folder:
    type: uri_folder
    path: azureml://datastores/workspaceblobstore/paths/
jobs:
  test_data:
    code: test-data
    command: python test_data.py ${{inputs.test_data_path}}
    environment: azureml:train-env@latest
    compute: azureml:aks-cluster
    inputs:
      test_data_path: ${{parent.inputs.test_data_folder}}
  register_data:
    command: az ml data create --name diabetes-mlops-data --path ${{inputs.training_data}} --resource-group AI-ML_RG --workspace-name ml-workspace
    environment: azureml:train-env@latest
    compute: azureml:aks-cluster
    inputs:
      training_data: ${{parent.jobs.inputs.test_data_folder}}
    outputs:
      register_data_output:
  train_model:
    code: model
    command: python train.py --training-data ${{inputs.training_data}} --reg-rate ${{inputs.reg_rate}}
    inputs:
      training_data: ${{parent.jobs.register_data.outputs.register_data_output}}
      reg_rate: 0.01
    environment: azureml:train-env@latest
    compute: azureml:aks-cluster
    experiment_name: mlops-diabetes-training
    description: Train a LR model with YML