$schema: https://azuremlschemas.azureedge.net/latest/kubernetesOnlineDeployment.schema.json
name: blue
type: kubernetes
endpoint_name: aks-endpoint
model:
  path: azureml:mlops-model@latest
code_configuration:
  code: ./onlinescoring/
  scoring_script: score.py
environment: azureml:deployment-env@latest
request_settings:
  request_timeout_ms: 3000
  max_queue_wait_ms: 3000
resources:
  requests:
    cpu: "0.1"
    memory: "0.1Gi"
  limits:
    cpu: "0.2"
    memory: "200Mi"
instance_count: 1
scale_settings:
  type: default