$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue
endpoint_name: diabetes-endpoint
model: azureml:mlops-model@latest
#code_configuration:
#  code: ./onlinescoring/
#  scoring_script: score.py
#environment: azureml:deployment-env@latest
instance_type: Standard_DS2_v2
instance_count: 1