name: Manually trigger a Data Test, an Azure Machine Learning Pipeline job and Deploy Model

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      run: az login --service-principal -u ${{secrets.AZURE_CLIENT_ID}} -p ${{secrets.AZURE_CLIENT_PASSWORD}} --tenant ${{secrets.AZURE_TENANT_ID}}
    - name: Register dataset
      run: az ml data create --file ./src/data.yml --resource-group AI-ML_RG --workspace-name aml-workspace
    - name: Test Data and Submit a Machine Learning Job
      run: az ml job create --file ./src/job-pipeline.yml --resource-group AI-ML_RG --workspace-name aml-workspace --stream -s
    - name: Create an Online Endpoint
      id: online-endpoint
      run: az ml online-endpoint create --file ./src/kubernetes-endpoint.yml --resource-group AI-ML_RG --workspace-name aml-workspace
      continue-on-error: true
    - name: Online Endpoint exists print
      if: steps.online-endpoint.outcome == 'failure'
      run: echo "endpoint exists"
    - name: Online Endpoint created print
      if: steps.online-endpoint.outcome == 'success'
      run: echo "endpoint created"
    - name: Check Deployments
      id: check-deployments
      run: az ml online-endpoint show --name aks-mlops-endpoint --resource-group AI-ML_RG --workspace-name aml-workspace > at.json
    - name: Create the first Deployment
      if: (contains('blue', jq '.traffic' at.json) == false) && (contains('green', jq '.traffic' at.json) == false)
      run: |
           az ml online-deployment create --file ./src/kubernetes-blue-deployment.yml --resource-group AI-ML_RG --workspace-name aml-workspace
           az ml online-endpoint update --file ./src/kubernetes-blue-endpoint-update.yml --resource-group AI-ML_RG --workspace-name aml-workspace
    - name: Create an Online Deployment Blue
      if: jq '.traffic.green' at.json == 100
      run: |
           az ml online-deployment create --file ./src/kubernetes-blue-deployment.yml --resource-group AI-ML_RG --workspace-name aml-workspace
           az ml online-endpoint update --file ./src/kubernetes-blue-endpoint-update.yml --resource-group AI-ML_RG --workspace-name aml-workspace
    - name: Create an Online Deployment Green
      if: jq '.traffic.blue' at.json == 100
      run: |
           az ml online-deployment create --file ./src/kubernetes-green-deployment.yml --resource-group AI-ML_RG --workspace-name aml-workspace
           az ml online-endpoint update --file ./src/kubernetes-green-endpoint-update.yml --resource-group AI-ML_RG --workspace-name aml-workspace
    - name: Delete Deployment Blue
      if: jq '.traffic.green' at.json == 100
      run: az ml online-deployment delete --endpoint-name aks-mlops-endpoint --name blue --resource-group AI-ML_RG --workspace-name aml-workspace --yes
    - name: Delete Deployment Green
      if: jq '.traffic.blue' at.json == 100
      run: az ml online-deployment delete --endpoint-name aks-mlops-endpoint --name green --resource-group AI-ML_RG --workspace-name aml-workspace --yes
