name: Trial Workflow

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      run: az login --service-principal -u ${{secrets.AZURE_CLIENT_ID}} -p ${{secrets.AZURE_CLIENT_PASSWORD}} --tenant ${{secrets.AZURE_TENANT_ID}}
    - name: Workspace Show
      id: workspace-output
      run: echo "output=$(az ml workspace show --name aml-workspace --resource-group AI-ML_RG)" >> "$GITHUB_ENV"
    - name: Workspace Print
      run: echo "$output"
