name: Trial Workflow

on:
  workflow_dispatch:

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      run: az login --service-principal -u ${{secrets.AZURE_CLIENT_ID}} -p ${{secrets.AZURE_CLIENT_PASSWORD}} --tenant ${{secrets.AZURE_TENANT_ID}}

  train:
    runs-on: ubuntu-latest
    steps:
    - name: Workspace Show
      id: workspace-output
      run: az ml workspace show --name aml-workspace --resource-group AI-ML_RG > at.json
    - name: Workspace Print
      run: echo "$(jq '.location' at.json)"
